version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    # extra_hosts:
    #   - "first:192.168.55.20"
    #   - "second:192.168.55.21"
    networks:
      kryolite:
        ipv4_address: 192.168.55.10

  kryolite-first:
    image: ghcr.io/kryolite-crypto/kryolite/daemon:1.2.4
    restart: "no"
    environment:
      - VIRTUAL_HOST=first
      - VIRTUAL_PORT=80
    volumes:
      - ./first/data:/kryolite/.kryolite
      - ./first/appsettings.json:/kryolite/appsettings.json
    extra_hosts:
      - "first:192.168.55.10"
      - "second:192.168.55.10"
    networks:
      kryolite:
        ipv4_address: 192.168.55.20

  kryolite-second:
    image: ghcr.io/kryolite-crypto/kryolite/daemon:1.2.4
    restart: "no"
    environment:
      - VIRTUAL_HOST=second
      - VIRTUAL_PORT=80
    volumes:
      - ./second/data:/kryolite/.kryolite
      - ./second/appsettings.json:/kryolite/appsettings.json
    extra_hosts:
      - "first:192.168.55.10"
      - "second:192.168.55.10"
    networks:
      kryolite:
        ipv4_address: 192.168.55.21

  kryolite-miner:
    image: ghcr.io/kryolite-crypto/kryolite/miner:1.2.4
    command:


networks:
  kryolite:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
